cuda: True
ngpu: 1
gpu_id: '0'
data_dir: './datasets/yt8m/Train'     # Your dataset path
video_flist: './filelists/Video_Name_List.txt'
audio_flist: './filelists/Audio_Name_List.txt'
workers: 4
batchSize: 40
checkpoint_folder: ./checkpoints
init_model: './checkpoints/LSTM_ATTENTION_state_epoch20.pth'
topk: 5
